
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Upload conan packages
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.arch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Write conan credentials
        run: |
          echo "CONAN_REMOTE_USER=${{ secrets.BDC_ARTIFACTORY_USER }}" >> .credentials
          echo "CONAN_REMOTE_TOKEN=${{ secrets.BDC_ARTIFACTORY_PAT }}" >> .credentials

      - name: Login to Artifactory Container Registry
        uses: docker/login-action@v3
        with:
          registry: artifactory.boschdevcloud.com
          username: ${{ secrets.BDC_ARTIFACTORY_USER }}
          password: ${{ secrets.BDC_ARTIFACTORY_PAT }}

      - name: Build devcontainer and publish conan packages
        uses: devcontainers/ci@v0.3
        with:
          platform: linux/${{ matrix.arch }}
          noCache: false
          push: never
          runCmd: |
            conan upload "*" --all -r sdv-bgsw-conan-virtual -c
